version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command: ["start", "--http-relative-path=/auth"]
    ports:
      - "8080:8080"
    volumes:
      - ./themes:/opt/keycloak/themes:ro
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
